### ISSUE TITLE
Doesn't support groups config properly

### ISSUE THREAD

**Issue by D3strukt0r** [marocchino/validate-dependabot#740]
this action failed when I started using groups, see the current config here: https://github.com/D3strukt0r/weleda-webcenter-text-export/blob/f0ce41f7d4effb1113b5e7a0192bc1363626cbef/.github/dependabot.yml

```yml
version: 2
updates:
  ...
  - package-ecosystem: "npm"
    ...
    groups:
      pwa-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
```

gives me following error

```
| keyword | message | dataPath |
| ------- | ------- | -------- |
| additionalProperties | should NOT have additional properties | .updates[1].groups['pwa-dependencies'] |
```

as you may see here though, the PR was successfully created: https://github.com/D3strukt0r/weleda-webcenter-text-export/pull/32

See docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
