### ISSUE TITLE
False negative: "Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'"

### ISSUE THREAD

**Issue by corneliusroemer** [marocchino/validate-dependabot#743]
Dependabot validate lets this through:

```
version: 2
updates:
  - package-ecosystem: docker
    directory: website
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
          update-types:
            - "minor"
            - "patch"
  - package-ecosystem: docker
    directories:
      - website
      - backend
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
          update-types:
            - "minor"
            - "patch"
```

even though dependabot itself complains with:
```
Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'
```

<img width="2014" alt="Brave Browser 2024-05-11 17 20 10" src="https://github.com/marocchino/validate-dependabot/assets/25161793/52d6f0b6-59cb-4f12-83e1-9aa95fec78dc">
